"""add unified hardt wallet

Revision ID: 0d96b7435434
Revises: 78629cfda143
Create Date: 2026-08-13 07:43:56.251394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d96b7435434'
down_revision: Union[str, Sequence[str], None] = '78629cfda143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=True)
    op.create_table('wallet_topups',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('amount_brl', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=120), nullable=True),
    sa.Column('external_reference', sa.String(length=120), nullable=False),
    sa.Column('pix_copy_paste', sa.Text(), nullable=True),
    sa.Column('pix_qr_code', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_topups_external_reference'), 'wallet_topups', ['external_reference'], unique=True)
    op.create_index(op.f('ix_wallet_topups_provider_payment_id'), 'wallet_topups', ['provider_payment_id'], unique=True)
    op.create_index(op.f('ix_wallet_topups_status'), 'wallet_topups', ['status'], unique=False)
    op.create_index(op.f('ix_wallet_topups_user_id'), 'wallet_topups', ['user_id'], unique=False)
    op.create_index(op.f('ix_wallet_topups_wallet_id'), 'wallet_topups', ['wallet_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('product_code', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_product_code'), 'wallet_transactions', ['product_code'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_reference'), 'wallet_transactions', ['reference'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_type'), 'wallet_transactions', ['type'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_transactions_wallet_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_type'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_reference'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_product_code'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_wallet_topups_wallet_id'), table_name='wallet_topups')
    op.drop_index(op.f('ix_wallet_topups_user_id'), table_name='wallet_topups')
    op.drop_index(op.f('ix_wallet_topups_status'), table_name='wallet_topups')
    op.drop_index(op.f('ix_wallet_topups_provider_payment_id'), table_name='wallet_topups')
    op.drop_index(op.f('ix_wallet_topups_external_reference'), table_name='wallet_topups')
    op.drop_table('wallet_topups')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_table('wallets')
    # ### end Alembic commands ###
