"""add purchase idempotency

Revision ID: 2f5e41f24ef3
Revises: 4eace642342c
Create Date: 2026-08-13 17:21:07.303373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f5e41f24ef3'
down_revision: Union[str, Sequence[str], None] = '4eace642342c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('idempotency_key', sa.String(length=120), nullable=False))
    op.create_index(op.f('ix_purchases_idempotency_key'), 'purchases', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchases_idempotency_key'), table_name='purchases')
    op.drop_column('purchases', 'idempotency_key')
    # ### end Alembic commands ###
