"""create download releases

Revision ID: 5f85a7f62557
Revises: 77824ea1ffb1
Create Date: 2026-07-31 12:10:48.432272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f85a7f62557'
down_revision: Union[str, Sequence[str], None] = '77824ea1ffb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_releases',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('architecture', sa.String(length=30), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'version', 'platform', 'architecture', name='uq_download_release_product_build')
    )
    op.create_index(op.f('ix_download_releases_is_active'), 'download_releases', ['is_active'], unique=False)
    op.create_index(op.f('ix_download_releases_platform'), 'download_releases', ['platform'], unique=False)
    op.create_index(op.f('ix_download_releases_product_id'), 'download_releases', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_download_releases_product_id'), table_name='download_releases')
    op.drop_index(op.f('ix_download_releases_platform'), table_name='download_releases')
    op.drop_index(op.f('ix_download_releases_is_active'), table_name='download_releases')
    op.drop_table('download_releases')
    # ### end Alembic commands ###
