"""add license sequence

Revision ID: 68afad497a4b
Revises: a7f9cf5b7859
Create Date: 2026-07-28 23:01:00.456074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68afad497a4b'
down_revision: Union[str, Sequence[str], None] = 'a7f9cf5b7859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licenses', sa.Column('license_sequence', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_licenses_license_sequence'), 'licenses', ['license_sequence'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_licenses_license_sequence'), table_name='licenses')
    op.drop_column('licenses', 'license_sequence')
    # ### end Alembic commands ###
