"""add device tracking fields

Revision ID: 77824ea1ffb1
Revises: 7cc0087b8988
Create Date: 2026-07-31 11:02:37.419937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77824ea1ffb1'
down_revision: Union[str, Sequence[str], None] = '7cc0087b8988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('app_version', sa.String(length=50), nullable=True))
    op.add_column('devices', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('devices', sa.Column('last_ip_address', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'last_ip_address')
    op.drop_column('devices', 'ip_address')
    op.drop_column('devices', 'app_version')
    # ### end Alembic commands ###
