"""create charges table

Revision ID: 7cc0087b8988
Revises: fc715c13e600
Create Date: 2026-07-30 17:30:21.816465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc0087b8988'
down_revision: Union[str, Sequence[str], None] = 'fc715c13e600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charges',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('license_id', sa.Uuid(), nullable=True),
    sa.Column('charge_number', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charges_charge_number'), 'charges', ['charge_number'], unique=True)
    op.create_index(op.f('ix_charges_due_at'), 'charges', ['due_at'], unique=False)
    op.create_index(op.f('ix_charges_external_reference'), 'charges', ['external_reference'], unique=True)
    op.create_index(op.f('ix_charges_license_id'), 'charges', ['license_id'], unique=False)
    op.create_index(op.f('ix_charges_product_id'), 'charges', ['product_id'], unique=False)
    op.create_index(op.f('ix_charges_status'), 'charges', ['status'], unique=False)
    op.create_index(op.f('ix_charges_user_id'), 'charges', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_charges_user_id'), table_name='charges')
    op.drop_index(op.f('ix_charges_status'), table_name='charges')
    op.drop_index(op.f('ix_charges_product_id'), table_name='charges')
    op.drop_index(op.f('ix_charges_license_id'), table_name='charges')
    op.drop_index(op.f('ix_charges_external_reference'), table_name='charges')
    op.drop_index(op.f('ix_charges_due_at'), table_name='charges')
    op.drop_index(op.f('ix_charges_charge_number'), table_name='charges')
    op.drop_table('charges')
    # ### end Alembic commands ###
