"""add asaas billing integration

Revision ID: 81e3908bdded
Revises: e7252fb523f5
Create Date: 2026-08-03 11:17:35.836244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81e3908bdded'
down_revision: Union[str, Sequence[str], None] = 'e7252fb523f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_subscriptions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('billing_cycle', sa.String(length=30), nullable=False),
    sa.Column('asaas_subscription_id', sa.String(length=80), nullable=True),
    sa.Column('latest_payment_id', sa.String(length=80), nullable=True),
    sa.Column('invoice_url', sa.Text(), nullable=True),
    sa.Column('next_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_subscriptions_asaas_subscription_id'), 'billing_subscriptions', ['asaas_subscription_id'], unique=True)
    op.create_index(op.f('ix_billing_subscriptions_latest_payment_id'), 'billing_subscriptions', ['latest_payment_id'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_product_id'), 'billing_subscriptions', ['product_id'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_status'), 'billing_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_user_id'), 'billing_subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billing_subscriptions_user_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_status'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_product_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_latest_payment_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_asaas_subscription_id'), table_name='billing_subscriptions')
    op.drop_table('billing_subscriptions')
    # ### end Alembic commands ###
