"""add smm order persistence

Revision ID: 98722ac313f4
Revises: 80e66cbf115e
Create Date: 2026-08-15 14:29:09.232068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98722ac313f4'
down_revision: Union[str, Sequence[str], None] = '80e66cbf115e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smm_orders',
    sa.Column('purchase_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=30), server_default='jap', nullable=False),
    sa.Column('provider_service_id', sa.String(length=80), nullable=False),
    sa.Column('provider_order_id', sa.String(length=120), nullable=True),
    sa.Column('service_name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('provider_rate_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('provider_cost_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('hardt_rate_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('hardt_price_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('usd_brl_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('amount_brl', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('provider_status', sa.String(length=50), server_default='not_submitted', nullable=False),
    sa.Column('start_count', sa.Integer(), nullable=True),
    sa.Column('remains', sa.Integer(), nullable=True),
    sa.Column('provider_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smm_orders_provider_order_id'), 'smm_orders', ['provider_order_id'], unique=True)
    op.create_index(op.f('ix_smm_orders_provider_service_id'), 'smm_orders', ['provider_service_id'], unique=False)
    op.create_index(op.f('ix_smm_orders_provider_status'), 'smm_orders', ['provider_status'], unique=False)
    op.create_index(op.f('ix_smm_orders_purchase_id'), 'smm_orders', ['purchase_id'], unique=True)
    op.alter_column('purchases', 'inventory_item_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Compras de serviço não possuem inventory_item_id.
    Para restaurar o schema legado NOT NULL, registros SMM
    precisam ser removidos junto com suas purchases.
    """

    op.execute(
        sa.text(
            """
            DELETE FROM purchases
            WHERE id IN (
                SELECT purchase_id
                FROM smm_orders
            );
            """
        )
    )

    op.drop_index(
        op.f("ix_smm_orders_purchase_id"),
        table_name="smm_orders",
    )
    op.drop_index(
        op.f("ix_smm_orders_provider_status"),
        table_name="smm_orders",
    )
    op.drop_index(
        op.f("ix_smm_orders_provider_service_id"),
        table_name="smm_orders",
    )
    op.drop_index(
        op.f("ix_smm_orders_provider_order_id"),
        table_name="smm_orders",
    )

    op.drop_table("smm_orders")

    op.alter_column(
        "purchases",
        "inventory_item_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
