"""add license number and issued at

Revision ID: a7f9cf5b7859
Revises: f799a52e37f0
Create Date: 2026-07-28 22:36:04.763894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f9cf5b7859'
down_revision: Union[str, Sequence[str], None] = 'f799a52e37f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licenses', sa.Column('license_number', sa.String(length=20), nullable=False))
    op.add_column('licenses', sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_licenses_license_number'), 'licenses', ['license_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_licenses_license_number'), table_name='licenses')
    op.drop_column('licenses', 'issued_at')
    op.drop_column('licenses', 'license_number')
    # ### end Alembic commands ###
