"""add encrypted license key

Revision ID: e7252fb523f5
Revises: 5f85a7f62557
Create Date: 2026-08-01 08:13:03.188590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7252fb523f5'
down_revision: Union[str, Sequence[str], None] = '5f85a7f62557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licenses', sa.Column('encrypted_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licenses', 'encrypted_key')
    # ### end Alembic commands ###
